// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxXqT2DwxxSJQAPjtNj6TI17f5pcOBJI',
    appId: '1:399890284958:web:99ce931b1e82024692168f',
    messagingSenderId: '399890284958',
    projectId: 'onboarding-580e8',
    authDomain: 'onboarding-580e8.firebaseapp.com',
    storageBucket: 'onboarding-580e8.appspot.com',
    measurementId: 'G-QB4EWYNF0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRvhiZ9V2TM-GuzjeOulVeY42ze7yWWOo',
    appId: '1:399890284958:android:2420f908bee011ef92168f',
    messagingSenderId: '399890284958',
    projectId: 'onboarding-580e8',
    storageBucket: 'onboarding-580e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZHqUuQiSOwN4JjbilgMa-6Beq8xKprtM',
    appId: '1:399890284958:ios:c5c3dfdb47be2efa92168f',
    messagingSenderId: '399890284958',
    projectId: 'onboarding-580e8',
    storageBucket: 'onboarding-580e8.appspot.com',
    iosBundleId: 'com.example.onboardScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZHqUuQiSOwN4JjbilgMa-6Beq8xKprtM',
    appId: '1:399890284958:ios:d340fd86d510c48092168f',
    messagingSenderId: '399890284958',
    projectId: 'onboarding-580e8',
    storageBucket: 'onboarding-580e8.appspot.com',
    iosBundleId: 'com.example.onboardScreen.RunnerTests',
  );
}
