// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavu2pUcO931GAt6SXTpz2Cyd1SiETjA4',
    appId: '1:906321350640:web:951e76032af4ed6e835735',
    messagingSenderId: '906321350640',
    projectId: 'email-auth-8d552',
    authDomain: 'email-auth-8d552.firebaseapp.com',
    storageBucket: 'email-auth-8d552.appspot.com',
    measurementId: 'G-LCJYLHFCRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGqS2UliiuZ5LSsrcBLrmMzJUq2sI9Fw',
    appId: '1:906321350640:android:f95bd8deaea456fb835735',
    messagingSenderId: '906321350640',
    projectId: 'email-auth-8d552',
    storageBucket: 'email-auth-8d552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCidlh3yCpdXvtPsFGUNWtgs7Mc6Po5mgk',
    appId: '1:906321350640:ios:f51a321c669fd0f5835735',
    messagingSenderId: '906321350640',
    projectId: 'email-auth-8d552',
    storageBucket: 'email-auth-8d552.appspot.com',
    androidClientId: '906321350640-vh3a9ijl1thirmec5jq123j8gvgva48k.apps.googleusercontent.com',
    iosClientId: '906321350640-vptssvih6940n815g80mftnugginteua.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCidlh3yCpdXvtPsFGUNWtgs7Mc6Po5mgk',
    appId: '1:906321350640:ios:49a017c2f7e97f5b835735',
    messagingSenderId: '906321350640',
    projectId: 'email-auth-8d552',
    storageBucket: 'email-auth-8d552.appspot.com',
    androidClientId: '906321350640-vh3a9ijl1thirmec5jq123j8gvgva48k.apps.googleusercontent.com',
    iosClientId: '906321350640-notogua3km3krcus26nmaa8rlfdkrslu.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailAuth.RunnerTests',
  );
}
