// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxmVwY8348Jxfrhzia_8pPelX2hEw11ds',
    appId: '1:363181075448:web:ee4ac39106822e59ba840d',
    messagingSenderId: '363181075448',
    projectId: 'phone-auth-f9b9a',
    authDomain: 'phone-auth-f9b9a.firebaseapp.com',
    storageBucket: 'phone-auth-f9b9a.appspot.com',
    measurementId: 'G-GNQBMJEM4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFJxLDagXMsp9EpIZljvBwvetJT-4vqXQ',
    appId: '1:363181075448:android:4ad2294b999dd55eba840d',
    messagingSenderId: '363181075448',
    projectId: 'phone-auth-f9b9a',
    storageBucket: 'phone-auth-f9b9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm7LBLsQcphN_w7m2WfjsB6j2SrdbFmV4',
    appId: '1:363181075448:ios:8e2deaceb89edb31ba840d',
    messagingSenderId: '363181075448',
    projectId: 'phone-auth-f9b9a',
    storageBucket: 'phone-auth-f9b9a.appspot.com',
    iosBundleId: 'com.example.phoneFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm7LBLsQcphN_w7m2WfjsB6j2SrdbFmV4',
    appId: '1:363181075448:ios:1a877abc4a7992a3ba840d',
    messagingSenderId: '363181075448',
    projectId: 'phone-auth-f9b9a',
    storageBucket: 'phone-auth-f9b9a.appspot.com',
    iosBundleId: 'com.example.phoneFirebase.RunnerTests',
  );
}
